apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ci-cd-app
  template:
    metadata:
      labels:
        app: ci-cd-app
    spec:
      containers:
        - name: app
          image: jhon027/ci-cd-demo:latest
          ports:
            - containerPort: 3000
          env:
            - name: APP_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_MESSAGE
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
